#!/bin/bash
#
# send_newsletter - Prüfen ob Prozess läuft falls nicht newsletter senden falls in Datenbank vorhanden
#
# @author Martin Mollay
# @last-changed 2011-06-10
#

#var=`ps aux | grep "php SendNewsletter.inc.php"`
var=`ps -eaf | grep "php SendNewsletter.inc.php" | wc -l`

if [ $var < "3" ]; then
        echo "Prozess wird gestartet"
        cd /var/www/ssi/center/ssi_newsletter/exec/
        /usr/bin/php SendNewsletter.inc.php
else
        echo "Prozess läuft"
fi
#send_newsletter (END) 
